name: Mimic Release Publish

on:
  release:
    types: [published]
    branches: [main]

jobs:
  log-release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Log package version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "Package version: $VERSION"

      - name: Show changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "Changelog:"
            cat CHANGELOG.md
          else
            echo "No changelog found."
          fi
